---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: primary
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik.jaymes.xyz
  namespace: traefik-system
spec:
  dnsNames:
    - "testing.jaymes.xyz"
    - "*.testing.jaymes.xyz"
  secretName: traefik.jaymes.xyz-tls
  issuerRef:
    name: primary
    kind: ClusterIssuer