apiVersion: v1
kind: Service
metadata:
  name: ldap
  namespace: traefik-system
spec:
  type: ClusterIP
  ports:
    - targetPort: 389
      port: 389
      name: ldap
    - targetPort: 636
      port: 636
      name: ldaps
---
apiVersion: v1
kind: Endpoints
metadata:
  # the name here should match the name of the Service
  name: ldap
  namespace: traefik-system
subsets:
  - addresses:
      - ip: "10.0.0.246"
    ports:
      - port: 389
        name: ldap
      - port: 636
        name: ldaps