apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik
  name: traefik
  namespace: traefik-system
spec:
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    nodePort: 30001
    port: 443
    protocol: TCP
    #targetPort: httpn
  - name: http
    nodePort: 30000
    port: 80
    protocol: TCP
    #targetPort: http
  selector:
    app: traefik
# sessionAffinity: None
  type: NodePort
