# elk
# otel agent
# etc...
repositories:
- name: prometheus-community 
  url: https://prometheus-community.github.io/helm-charts
- name: kubernetes-dashboard
  url: https://kubernetes.github.io/dashboard/

releases:
- name: prometheus
  chart: prometheus-community/kube-prometheus-stack
- name: kubernetes-dashboard
  chart: kubernetes-dashboard/kubernetes-dashboard
  namespace: kubernetes-dashboard
  values:
  - ./values/dashboard.yaml