---
- name: common | set variables
  ansible.builtin.include_vars: '{{ item }}'
  tags:
    - common
    - network
    - firewall
    - ntp
    - packages
    - auto-updates
    - users
  with_first_found:
    - "{{ ansible_facts['os_family'] }}.yml"
    - default.yml

- name: common | populate service facts
  ansible.builtin.service_facts:
  tags:
    - common

# Network
- name: network
  import_tasks: network.yml
  tags:
    - common
    - network

# NTP
- name: ntp
  import_tasks: ntp.yml
  tags:
    - common
    - ntp

# Packages
- name: packages
  import_tasks: packages.yml
  tags:
    - common
    - packages

# Users
- name: users
  import_tasks: users.yml
  tags:
    - common
    - users

# Flush Handlers
- name: common | flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - common