# elk
# otel agent
# etc...
repositories:
- name: prometheus-community 
  url: https://prometheus-community.github.io/helm-charts
- name: kubernetes-dashboard
  url: https://kubernetes.github.io/dashboard/
- name: jetstack
  url: https://charts.jetstack.io
- name: open-telemetry
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
releases:

# https://github.com/open-telemetry/opentelemetry-helm-charts

- name: prometheus
  chart: prometheus-community/kube-prometheus-stack

- name: opentelemetry-collector
  chart: open-telemetry/opentelemetry-collector
  values:
  - ./values/opentelemetry.yaml
- name: kubernetes-dashboard
  chart: kubernetes-dashboard/kubernetes-dashboard
  namespace: kubernetes-dashboard
  values:
  - ./values/dashboard.yaml
# https://artifacthub.io/packages/helm/cert-manager/cert-manage
- name: cert-manager
  chart: jetstack/cert-manager
  namespace: cert-manager
  createNamespace: true
  version: v1.8.2
  values:
  - ./values/cert-manager.yaml
# https://artifacthub.io/packages/helm/bitnami/redis