service:
  enabled: false
  #type: NodePort
ports:
  web:
    nodePort: 30000
  websecure:
    nodePort: 30001
nodeSelector:
  ingress-ready: 'true'
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Equal
    effect: NoSchedule