repositories:
# To use official "stable" charts a.k.a https://github.com/helm/charts/tree/master/stable
- name: stable
  url: https://charts.helm.sh/stable
- name: authelia
  url: https://charts.authelia.com/
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
# https://artifacthub.io/packages/helm/traefik/traefik
- name: traefik
  namespace: traefik-system
  chart: stable/traefik
  values:
  - ./values/traefik2.yaml
# https://github.com/authelia/chartrepo/tree/master/charts/authelia
- name: authelia
  version: 0.8.38
  namespace: traefik-system
  chart: authelia/authelia
  values:
  - ./values/authelia.yaml
# https://artifacthub.io/packages/helm/bitnami/redis
- name: authelia-redis
  namespace: traefik-system
  chart: bitnami/redis
  values:
  - ./values/authelia-redis.yaml