kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
  annotations: {}
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
  annotations: 
    storageclass.kubernetes.io/is-default-class: 'true'
#  managedFields:
#    - manager: kubectl-client-side-apply
#      operation: Update
#      apiVersion: storage.k8s.io/v1
#      time: '2022-07-20T21:41:52Z'
#      fieldsType: FieldsV1
#      fieldsV1:
#        f:metadata:
#          f:annotations:
#            .: {}
#            f:kubectl.kubernetes.io/last-applied-configuration: {}
#            f:storageclass.kubernetes.io/is-default-class: {}
#        f:provisioner: {}
#        f:reclaimPolicy: {}
#        f:volumeBindingMode: {}
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true